"""initial_schema"""
from alembic import op
import sqlalchemy as sa

revision = '0b9345094ff9'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('districts',
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'name')
    )
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('government_schemes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=False),
    sa.Column('application_process', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_schemes_state_id'), 'government_schemes', ['state_id'], unique=False)
    op.create_table('ngos',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('availability', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngos_district_id'), 'ngos', ['district_id'], unique=False)
    op.create_table('prosecutors',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_documents',
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['government_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_documents_scheme_id'), 'scheme_documents', ['scheme_id'], unique=False)
    op.create_table('scheme_eligibility',
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['government_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_eligibility_scheme_id'), 'scheme_eligibility', ['scheme_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('VICTIM', 'COUNSELLOR', 'LEGAL_OFFICER', 'DISTRICT_ADMIN', 'STATE_ADMIN', 'NATIONAL_ADMIN', name='role', native_enum=False), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('state_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role != 'DISTRICT_ADMIN' OR district_id IS NOT NULL"),
    sa.CheckConstraint("role != 'STATE_ADMIN' OR state_id IS NOT NULL"),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_state_id'), 'users', ['state_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('counsellors',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('legal_officers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ngo_languages',
    sa.Column('ngo_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ngo_id', 'language')
    )
    op.create_index(op.f('ix_ngo_languages_ngo_id'), 'ngo_languages', ['ngo_id'], unique=False)
    op.create_table('ngo_services',
    sa.Column('ngo_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ngo_id', 'service')
    )
    op.create_index(op.f('ix_ngo_services_ngo_id'), 'ngo_services', ['ngo_id'], unique=False)
    op.create_table('victims',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('annual_income', sa.Integer(), nullable=True),
    sa.Column('support_category', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age IS NULL OR (age >= 0 AND age <= 130)'),
    sa.CheckConstraint('annual_income IS NULL OR annual_income >= 0'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_victims_district_id'), 'victims', ['district_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=60), nullable=False),
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=False),
    sa.Column('fir_number', sa.String(length=80), nullable=True),
    sa.Column('fir_date', sa.Date(), nullable=True),
    sa.Column('police_station', sa.String(length=160), nullable=True),
    sa.Column('investigation_status', sa.String(length=40), nullable=False),
    sa.Column('chargesheet_date', sa.Date(), nullable=True),
    sa.Column('chargesheet_reference', sa.String(length=160), nullable=True),
    sa.Column('court', sa.String(length=160), nullable=True),
    sa.Column('prosecutor_id', sa.String(length=36), nullable=True),
    sa.Column('legal_officer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('compensation_status', sa.String(length=40), nullable=False),
    sa.Column('rehabilitation_status', sa.String(length=40), nullable=False),
    sa.Column('protection_status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['legal_officer_id'], ['legal_officers.id'], ),
    sa.ForeignKeyConstraint(['prosecutor_id'], ['prosecutors.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_district_id'), 'cases', ['district_id'], unique=False)
    op.create_index(op.f('ix_cases_legal_officer_id'), 'cases', ['legal_officer_id'], unique=False)
    op.create_index(op.f('ix_cases_victim_id'), 'cases', ['victim_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_victim_id'), 'chat_messages', ['victim_id'], unique=False)
    op.create_table('counsellor_assignments',
    sa.Column('counsellor_id', sa.String(length=36), nullable=False),
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counsellor_id'], ['counsellors.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counsellor_id', 'victim_id')
    )
    op.create_index(op.f('ix_counsellor_assignments_counsellor_id'), 'counsellor_assignments', ['counsellor_id'], unique=False)
    op.create_index(op.f('ix_counsellor_assignments_victim_id'), 'counsellor_assignments', ['victim_id'], unique=False)
    op.create_table('distress_assessments',
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('instrument', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distress_assessments_victim_id'), 'distress_assessments', ['victim_id'], unique=False)
    op.create_table('distress_predictions',
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.CheckConstraint('score >= 0 AND score <= 100'),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_distress_predictions_observed_at'), 'distress_predictions', ['observed_at'], unique=False)
    op.create_index(op.f('ix_distress_predictions_victim_id'), 'distress_predictions', ['victim_id'], unique=False)
    op.create_table('followups',
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('counsellor_id', sa.String(length=36), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counsellor_id'], ['counsellors.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_due_at'), 'followups', ['due_at'], unique=False)
    op.create_index(op.f('ix_followups_victim_id'), 'followups', ['victim_id'], unique=False)
    op.create_table('alerts',
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['distress_predictions.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index(op.f('ix_alerts_victim_id'), 'alerts', ['victim_id'], unique=False)
    op.create_table('case_documents',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_documents_case_id'), 'case_documents', ['case_id'], unique=False)
    op.create_table('case_events',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_events_occurred_at'), 'case_events', ['occurred_at'], unique=False)
    op.create_table('case_permissions',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('legal_officer_id', sa.String(length=36), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['legal_officer_id'], ['legal_officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'legal_officer_id')
    )
    op.create_index(op.f('ix_case_permissions_case_id'), 'case_permissions', ['case_id'], unique=False)
    op.create_table('case_sections',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('act', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'act', 'section')
    )
    op.create_index(op.f('ix_case_sections_case_id'), 'case_sections', ['case_id'], unique=False)
    op.create_table('counselling_notes',
    sa.Column('followup_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['followup_id'], ['followups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('followup_id')
    )
    op.create_table('hearings',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hearings_case_id'), 'hearings', ['case_id'], unique=False)
    op.create_index(op.f('ix_hearings_scheduled_at'), 'hearings', ['scheduled_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'alert_id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_hearings_scheduled_at'), table_name='hearings')
    op.drop_index(op.f('ix_hearings_case_id'), table_name='hearings')
    op.drop_table('hearings')
    op.drop_table('counselling_notes')
    op.drop_index(op.f('ix_case_sections_case_id'), table_name='case_sections')
    op.drop_table('case_sections')
    op.drop_index(op.f('ix_case_permissions_case_id'), table_name='case_permissions')
    op.drop_table('case_permissions')
    op.drop_index(op.f('ix_case_events_occurred_at'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_case_documents_case_id'), table_name='case_documents')
    op.drop_table('case_documents')
    op.drop_index(op.f('ix_alerts_victim_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_followups_victim_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_due_at'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_distress_predictions_victim_id'), table_name='distress_predictions')
    op.drop_index(op.f('ix_distress_predictions_observed_at'), table_name='distress_predictions')
    op.drop_table('distress_predictions')
    op.drop_index(op.f('ix_distress_assessments_victim_id'), table_name='distress_assessments')
    op.drop_table('distress_assessments')
    op.drop_index(op.f('ix_counsellor_assignments_victim_id'), table_name='counsellor_assignments')
    op.drop_index(op.f('ix_counsellor_assignments_counsellor_id'), table_name='counsellor_assignments')
    op.drop_table('counsellor_assignments')
    op.drop_index(op.f('ix_chat_messages_victim_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_cases_victim_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_legal_officer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_district_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_victims_district_id'), table_name='victims')
    op.drop_table('victims')
    op.drop_index(op.f('ix_ngo_services_ngo_id'), table_name='ngo_services')
    op.drop_table('ngo_services')
    op.drop_index(op.f('ix_ngo_languages_ngo_id'), table_name='ngo_languages')
    op.drop_table('ngo_languages')
    op.drop_table('legal_officers')
    op.drop_table('counsellors')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_state_id'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheme_eligibility_scheme_id'), table_name='scheme_eligibility')
    op.drop_table('scheme_eligibility')
    op.drop_index(op.f('ix_scheme_documents_scheme_id'), table_name='scheme_documents')
    op.drop_table('scheme_documents')
    op.drop_table('prosecutors')
    op.drop_index(op.f('ix_ngos_district_id'), table_name='ngos')
    op.drop_table('ngos')
    op.drop_index(op.f('ix_government_schemes_state_id'), table_name='government_schemes')
    op.drop_table('government_schemes')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('states')
    # ### end Alembic commands ###
